apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: goofydo
data:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres.goofydo.svc.cluster.local:5432/appdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: goofydo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:8.8.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for Keycloak..."
              until curl -k -s -o /dev/null -w "%{http_code}" \
                http://keycloak:8080/auth/realms/todo/.well-known/openid-configuration \
                | grep -q '^200$'; do
                echo "Keycloak not ready yet, sleeping 5s..."
                sleep 5
              done
              echo "Keycloak is up"
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: backend
          # image: ghcr.io/dhbw-tobi-felix/goofy-do/goofydo-backend:latest
          image: goofydo-backend:prod
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-Djava.net.preferIPv4Stack=true"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: goofydo
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080